/**
 * Generates `src/tenant-ddl.generated.ts` from the Drizzle tenant schema — the
 * authoritative DDL bundle a new tenant schema is provisioned with (DB-001).
 *
 * Run: pnpm --filter @hrms-app/db gen:tenant-ddl
 *
 * The generated file is a plain string array (no drizzle-kit at runtime) and is
 * checked in; the parity test (src/__tests__/tenant-ddl.test.ts) fails if it
 * drifts from the schema, forcing a regenerate.
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { buildTenantDdl } from "../src/tenant-ddl-builder";

const here = dirname(fileURLToPath(import.meta.url));

async function main() {
  const statements = await buildTenantDdl();
  const banner =
    "// AUTO-GENERATED by scripts/generate-tenant-ddl.ts — do not edit by hand.\n" +
    "// Regenerate: pnpm --filter @hrms-app/db gen:tenant-ddl\n" +
    "// Source of truth: src/schema/tenant/*.ts (+ EXTRA_STATEMENTS in tenant-ddl-builder.ts).\n";
  const body =
    `${banner}\n` +
    "export const TENANT_DDL_STATEMENTS: string[] = [\n" +
    statements.map((s) => `  ${JSON.stringify(s)},`).join("\n") +
    "\n];\n";
  const out = join(here, "..", "src", "tenant-ddl.generated.ts");
  writeFileSync(out, body, "utf8");
  // eslint-disable-next-line no-console
  console.log(`Wrote ${statements.length} statements to ${out}`);
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
